### ISSUE TITLE
Documento de visão

### ISSUE THREAD

**Issue by juliapessoasouza** [Non-Devs/django-ds#8]
Eu, como usuário, gostaria de ter acesso ao documento de visão do projeto

Critérios de aceitação:

- [x] Introdução
- [x] Posicionamento
- [x] Descrições da Parte Interessada e do Usuário
- [x] Visão Geral do Produto
- [x] Recursos do Produto
- [x] Restrições

**Comment by sconetto** [comment]
@juliapessoasouza 
vamos usar esse como modelo: https://www.ibm.com/support/knowledgecenter/pt-br/SSYMRC_4.0.6/com.ibm.rational.rrm.help.doc/topics/r_vision_doc.html

Alguns tópicos vamos retirar, mas vamos conversando ao longo da semana
